[[redirects]]
  from = "/authors"
  to = "/contributors"
  status = 301
  force = true

[[redirects]]
  from = "/author/*"
  to = "/contributor/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    # Highest weight (20) - Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' *.disqus.com *.posthog.com *.convertkit.com *.cloudflareinsights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self'; connect-src 'self' *.disqus.com *.posthog.com *.convertkit.com *.cloudflareinsights.com; frame-ancestors 'none'; form-action 'self'"
    
    # High weight (15) - HTTP Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Medium-high weight (10) - Cross-Origin Policies
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    
    # Medium weight (8) - Security Headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    
    # Medium weight (7) - Privacy and Permissions
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    
    # Lower weight (5 and 3) - Additional Security
    X-DNS-Prefetch-Control = "on"

    # Leaking headers
    Server = ""